server:
  port: 5656
  compression:
    enabled: true

spring:
  application:
    name: personalApp
  datasource:
    platform: oracle
    driver-class-name: oracle.jdbc.OracleDriver
    name: oracle
  jpa:
    database: ORACLE
    show-sql: ${LOG_SHOW_SQL:true}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone = TimeZone
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true

